"""Read default renderer visibility from complete cafe prefabs."""
import argparse
import json
import pathlib
import re
import UnityPy

parser = argparse.ArgumentParser()
parser.add_argument('--bundles', type=pathlib.Path, required=True)
parser.add_argument('--inventory', type=pathlib.Path, required=True)
parser.add_argument('--output', type=pathlib.Path, required=True)
args = parser.parse_args()
profiles, failures = [], []
records = json.loads(args.inventory.read_text(encoding='utf8'))['bundles']
for record in records:
    names = {m['name'] for m in record['models'] if m['name'].startswith('Cafe_')}
    if not names:
        continue
    try:
        env = UnityPy.load(str(args.bundles / record['file']))
        for obj in env.objects:
            if obj.type.name != 'Animator':
                continue
            go = obj.read().m_GameObject.read()
            if go.m_Name not in names:
                continue
            hidden = []
            def visit(game_object, parent_active=True):
                active = parent_active and game_object.m_IsActive
                for entry in game_object.m_Component:
                    component = entry.component
                    if component.type.name == 'Transform':
                        for child in component.read().m_Children:
                            visit(child.read().m_GameObject.read(), active)
                    elif component.type.name in ('MeshRenderer', 'SkinnedMeshRenderer'):
                        renderer = component.read()
                        if not renderer.m_Enabled or not active:
                            hidden.append(game_object.m_Name)
            visit(go)
            if hidden:
                profiles.append({'root': go.m_Name, 'hiddenNodes': sorted(set(hidden)), 'source': record['file']})
    except Exception as error:
        failures.append({'source': record['file'], 'error': str(error)})
if failures:
    raise RuntimeError(json.dumps(failures, ensure_ascii=False))
profiles.sort(key=lambda item: item['root'])
args.output.write_text('// Generated by tools/game-assets/extract-face-profiles.py.\n'
    '// Exact cafe prefab roots and source renderer/ancestor visibility only.\n'
    'export const FACE_PROFILES = ' + json.dumps(profiles, ensure_ascii=False, indent=2) + ';\n', encoding='utf8')
print(json.dumps({'profiles': len(profiles), 'hiddenRenderers': sum(len(p['hiddenNodes']) for p in profiles)}))
